date: today
knitr:
  opts_chunk:
    tidy: 'styler'
    tidy.opts: list(scope = "line_breaks")
    # style = tidyverse_style, scope = "spaces")
# opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
#     knitr.duplicate.label: 'allow'
# project:
#   lib-dir: ..
output:
  html_document
execute:
  warning: false
  cache: true
format:
  html:
    toc: true
    toc-depth: 2
    toc-highlight: true
    # toc_float: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    # toc-title: "Content"
    page-layout: full
    number-sections: true
    # css: style.css
    code-overflow: wrap
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    code-line-numbers: true
    code-block-border-left: "blue"
