# setup ----
source("~/R_code_github/useful_functions_module.r")
# my_paths <- set_work_dir()

dir_to_comb <- "~/R_code_github/fishing_effort_location"

r_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.R")

rmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.Rmd")

qmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.qmd")

# prepare all pieces ----
## Add headers to the flat file to be converted by knitr ----
# In this code, 'flat_file_r_with_headers_text' is generated by modifying the text content read from the file specified by 'r_file_name'. The 'gsub' function is used to replace specific patterns in the text:
#
# It searches for lines that start with one or more '#' symbols followed by a space, captures the content after that, and then captures a line with "----" at the end.
# It replaces this pattern with a modified format, adding "#'" at the beginning of the first line for headers,
# "#+" at the beginning of the second line for chunk labels,
# and copying the pattern on the third line to keep comments in place.
# This transformation is used to adapt R script file to an R Markdown format by converting header lines to Roxygen-style comments.
#

flat_file_r_with_headers_text <-
  gsub("^(#+ )(.+)(----)",
       "#' \\1\\2\\\n#+ \\2\\\n\\1\\2\\3",
       readLines(r_file_name))

# head(flat_file_r_with_headers_text)

# flat_file_r_with_headers_text_safe_slash <-
#   gsub("\\([^0-9 ])",
#        "/\\1",
#        flat_file_r_with_headers_text)

# head(flat_file_r_with_headers_text_safe_slash)

# glimpse(flat_file_r_with_headers)
 # chr [1:11952] "#' ## Current file: useful_functions_module.r" "" "" ...

# convert to Rmd ----
# The 'knitr::spin' function is used to create an R Markdown (Rmd) file, but the 'knit' argument is set to 'FALSE', indicating that the document should not be fully knitted. Instead, this function generates an Rmd file from the R script without executing the code chunks.

tic("rmd_text")
rmd_text <-
  knitr::spin(text = flat_file_r_with_headers_text,
              knit = FALSE)
toc()
# rmd_text: 0.11 sec elapsed

# str(rmd_text)
#  chr [1:12684] "## Current file: useful_functions_module.r" ...

pre_text <- '
---
title: "Fishing effort locations heatmap"
date: today
# project:
#   lib-dir: ..
output:
  html_document
execute:
  warning: false
  cache: true
format:
  html:
    toc: true
    toc-depth: 2
    css: style.css
    code-overflow: wrap
    code-fold: true
    code-summary: "Show the code"
    code-line-numbers: true
---
'

# Setup
setup_text <- "
```{r no cache setup, results='hide', message=FALSE, warning=FALSE, cache=FALSE}
# setup ----
library(mapview)
library(knitr)
```
"

# combine pieces into a Quarto file ----

cat(
  pre_text,
  file = qmd_file_name,
  # append = TRUE,
  sep = "\n"
)

cat(
  setup_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)

cat(
  rmd_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)
