# setup ----
source("~/R_code_github/useful_functions_module.r")
# my_paths <- set_work_dir()

dir_to_comb <- "~/R_code_github/fishing_effort_location"

r_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.R")

rmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.Rmd")

qmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.qmd")

# prepare all pieces ----
## Add headers to the flat file to be converted by knitr ----
# In this code, 'flat_file_r_with_headers_text' is generated by modifying the text content read from the file specified by 'r_file_name'. The 'gsub' function is used to replace specific patterns in the text:
#
# It searches for lines that start with one or more '#' symbols followed by a space, captures the content after that, and then captures a line with "----" at the end.
# It replaces this pattern with a modified format, adding "#'" at the beginning of the first line for headers,
# and copying the pattern on the second line to keep comments in place.
# This transformation is used to adapt R script file to an R Markdown format by converting header lines to Roxygen-style comments.
#

flat_file_r_text <-
  readLines(r_file_name)

pattern_to_add_md_headers <- "#' \\1\\2"
pattern_to_add_md_chunk_labels <- "#+ \\2"
pattern_to_repeat_the_original <- "\\1\\2\\3"

flat_file_r_with_headers_text <-
  gsub("^(#+ )(.+)(----)",
       paste(pattern_to_add_md_headers,
              pattern_to_add_md_chunk_labels,
              pattern_to_repeat_the_original,
              sep = "\\\n"),
       flat_file_r_text)

j_test_text1 <- grep("Jeannette", flat_file_r_with_headers_text, value = T)

flat_file_r_with_headers_text <-
  gsub("source\\(", "# source(", flat_file_r_with_headers_text)

# In this code, 'flat_file_r_with_headers_text' is modified using the 'gsub' function to replace specific patterns in the text. The pattern being searched for is defined using a regular expression:
#
# It searches for lines starting with "#+" followed by a space and captures the content after that.
# It captures a single quote or a slash.
# It captures more content.
# It captures a newline character.

flat_file_r_with_headers_text <-
  gsub(
    "(#\\+ )([^'/]+)(['/])(.+)(\\\n)",
    "\\1\\2_\\4\\5",
    flat_file_r_with_headers_text
  )


# convert to Rmd ----
# The 'knitr::spin' function is used to create an R Markdown (Rmd) file, but the 'knit' argument is set to 'FALSE', indicating that the document should not be fully knitted. Instead, this function generates an Rmd file from the R script without executing the code chunks.

tic("rmd_text")
rmd_text <-
  knitr::spin(text = flat_file_r_with_headers_text,
              knit = FALSE,
              format = 'qmd')
toc()
# rmd_text: 0.11 sec elapsed

# str(rmd_text)
#  chr [1:12684] "## Current file: useful_functions_module.r" ...

pre_text <- '
---
title: "Fishing effort locations heatmap"
---
'

# Setup
setup_text <- "
```{r no cache setup, results='hide', message=FALSE, warning=FALSE, cache=FALSE}
library(knitr)
```
"

# combine pieces into a Quarto file ----

cat(
  pre_text,
  file = qmd_file_name,
  # append = TRUE,
  sep = "\n"
)

cat(
  setup_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)

cat(
  rmd_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)

