# setup ----
source("~/R_code_github/useful_functions_module.r")
# my_paths <- set_work_dir()

dir_to_comb <- "~/R_code_github/fishing_effort_location"

r_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.R")

rmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.Rmd")

qmd_file_name <-
  file.path(dir_to_comb, "flat_file_heatmap.qmd")

# prepare all pieces ----
## Add headers to the flat file to be converted by knitr ----
# In this code, 'flat_file_r_with_headers_text' is generated by modifying the text content read from the file specified by 'r_file_name'. The 'gsub' function is used to replace specific patterns in the text:
#
# It searches for lines that start with one or more '#' symbols followed by a space, captures the content after that, and then captures a line with "----" at the end.
# It replaces this pattern with a modified format, adding "#'" at the beginning of the first line for headers,
# and copying the pattern on the second line to keep comments in place.
# This transformation is used to adapt R script file to an R Markdown format by converting header lines to Roxygen-style comments.
#

flat_file_r_text <-
  readLines(r_file_name)

# head_flat_file_r_text <-
#   head(flat_file_r_text)

set.seed(1000)

pattern_to_add_md_headers <- "#' \\1\\2"
pattern_to_add_md_chunk_labels <- "#+ \\2"
# pattern_to_add_md_chunk_labels <- paste0("#+ \\2", sample(1:10000, 1))
pattern_to_repeat_the_original <- "\\1\\2\\3"

# "#' \\1\\2\\\n#+ \\2\\\n\\1\\2\\3"

flat_file_r_with_headers_text <-
  gsub("^(#+ )(.+)(----)",
       paste(pattern_to_add_md_headers,
              pattern_to_add_md_chunk_labels,
              pattern_to_repeat_the_original,
              sep = "\\\n"),
       flat_file_r_text)

j_test_text1 <- grep("Jeannette", flat_file_r_with_headers_text, value = T)

# head(flat_file_r_with_headers_text)
# flat_file_r_with_headers_text <-
#   gsub("^(#+ )(.+)(----)",
#        "#' \\1\\2\\\n\\1\\2\\3",
#        flat_file_r_text)

flat_file_r_with_headers_text <-
  gsub("source\\(", "# source(", flat_file_r_with_headers_text)

# hh <- head(flat_file_r_with_headers_text)

# works
  # gsub("(#[+] )(.+)(#)",
  #     "\\1 HHHH\\\n\\3",
  #      hh)

flat_file_r_with_headers_text <-
  gsub(
    "(#\\+ )([^']+)(['])(.+)(\\\n)",
    "\\1\\2_\\4\\5",
    flat_file_r_with_headers_text
  )

# orginal
# grep("Jeannette", flat_file_r_text)
# [1] 2235 2237 3709
# [1] "# read Jeannette's file ----"

# test_text <- flat_file_r_text[2232:2237]

# grep("Jeannette", flat_file_r_with_headers_text, value = T)
# [1] "#' # read Jeannette's file \n#+ read Jeannette_s file \n#\n read Jeannette's file ----"

# convert to Rmd ----
# The 'knitr::spin' function is used to create an R Markdown (Rmd) file, but the 'knit' argument is set to 'FALSE', indicating that the document should not be fully knitted. Instead, this function generates an Rmd file from the R script without executing the code chunks.
# flat_file_r_with_headers_text[2309:2315]

# grep("Jeannette", flat_file_r_with_headers_text, value = T)

tic("rmd_text")
rmd_text <-
  knitr::spin(text = flat_file_r_with_headers_text,
              knit = FALSE)
toc()
# rmd_text: 0.11 sec elapsed

# str(rmd_text)
#  chr [1:12684] "## Current file: useful_functions_module.r" ...

pre_text <- '
---
title: "Fishing effort locations heatmap"
date: today
# project:
#   lib-dir: ..
output:
  html_document
execute:
  warning: false
  cache: true
format:
  html:
    toc: true
    toc-depth: 2
    css: style.css
    code-overflow: wrap
    code-fold: true
    code-summary: "Show the code"
    code-line-numbers: true
---
'

# Setup
setup_text <- "
```{r no cache setup, results='hide', message=FALSE, warning=FALSE, cache=FALSE}
# setup ----
library(mapview)
library(knitr)
```
"

# combine pieces into a Quarto file ----

cat(
  pre_text,
  file = qmd_file_name,
  # append = TRUE,
  sep = "\n"
)

cat(
  setup_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)

cat(
  rmd_text,
  file = qmd_file_name,
  append = TRUE,
  sep = "\n"
)

